### ISSUE TITLE
How does Enso work

### ISSUE THREAD

**Issue by yairchu** [yairchu/awesome-structure-editors#16]
Is the following understanding correct:

* Enso stores the code as a data structure in a database
* The data structure gets converted to text for the textual syntax
* The code is auto-formatted. The user didn't choose how to split lines
* When a user edits the textual syntax the text gets re-parsed and the database is updated

If so then I should probably put it in the main list of structure editors, rather than in the visual languages section.
If anyone knowledgable could validate this that would be helpful! @wdanilo @iamrecursion

**Comment by wdanilo** [comment]
That's incorrect! :)

- Enso stores all of the data in the text file that is human readable. Additional information, like node position, is stored at the end of the file as metadata. You can remove the metadata and the nodes will be auto-formatted on the screen.
- The code can be formatted by the user. We store the spacing information and when we are regenerating the code, we are preserving that. We will ship an auto-formatter for the code, but it will be optional for the user.
- We have `Code <-> AST <-> Graph` isomorphic conversions. Every representation contains ALL the data, so you can store everything in AST, in Graph, or in Code.

Does it clarify how it works @yairchu ? :)

**Comment by wdanilo** [comment]
Btw, @yairchu, I think that Enso should be included in the "structural editor" list as well. Our nodes are expressions and they allow you to modify parts of the program in a structural, visual way (either by typing or by connecting edges to parts of the expressions) – our visual IDE allows you to structurally track parts of the expressions and treat them as inputs to your nodes.

**Comment by yairchu** [comment]
@wdanilo you make a good case, I've merged the visual projects in and added flags for visual programming and text-files based programming. As long as the project isn't just traditional text-based programming and it is for a real programming language, it should be included in the table. Thanks for the feedback and if you have more suggestions feel free to share!

**Comment by wdanilo** [comment]
@yairchu thanks so much, I really appreciate your thoughts and help here! ❤️
