### ISSUE TITLE
Add ProjectIt/Freon

### ISSUE THREAD

**Issue by dslmeinte** [yairchu/awesome-structure-editors#18]
https://www.projectit.org/ is missing from the list: could you add it?

**Comment by yairchu** [comment]
Definitely.
Btw do they have some demo video or screenshots somewhere? I'm trying the build instructions now to figure out how it looks like.

**Comment by yairchu** [comment]
Couldn't run it and opened an issue for now https://github.com/projectit-org/ProjectIt/issues/282

When I get a grasp of what it is / how it looks like, I'll be able to add it

**Comment by dslmeinte** [comment]
Currently, no screenshots or demo videos are available. I checked yesterday that the example project https://github.com/projectit-org/ProjectIt-example does work, so you might want to have a try with that?

(I happen to know that the creators are currently offline-ish, and I don't want to pressure them in any way.)

**Comment by dslmeinte** [comment]
Thanks, @yairchu !

**Comment by yairchu** [comment]
Feel free to send corrections!

I marked it as "⌨️ Text editing like UX" because it works like text editing for some things like numerical expressions (i.e "1 + 2 * 3 + 4"), but for some other things, like referring to a variable doesn't currently work by just typing in its name.
